name: CI/CD for Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Adjust according to your PHP version

    - name: Install dependencies
      run: |
        composer install --no-progress --prefer-dist
        php artisan key:generate

    # - name: Run tests
    #   run: php artisan test

    - name: Install rsync
      run: sudo apt-get install rsync

    - name: Deploy to cPanel
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        # Add the private key to the ssh-agent
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        eval "$(ssh-agent -s)"
        ssh-add private_key

        # Deploy using rsync over SSH
        RSYNC_OPTIONS="--archive --verbose --delete"
        rsync $RSYNC_OPTIONS -e "ssh -o StrictHostKeyChecking=no -i private_key" ./ $SSH_USERNAME@$SSH_HOST:/home/$SSH_USERNAME/public_html/sysnewv2.medyouin.com/

        # Execute commands on the server
        ssh -o StrictHostKeyChecking=no -i private_key $SSH_USERNAME@$SSH_HOST << 'EOF'
          cd /home/$SSH_USERNAME/public_html/sysnewv2.medyouin.com
          composer install --no-dev
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
        EOF

    - name: Clean up
      run: rm private_key